### ISSUE TITLE
Error: --dataset should contain a pathname of a .loom or .h5 file

### ISSUE THREAD

**Issue by tianlt** [dynverse/dyno#122]
Hi, Thank you for presenting such a good tool. I have encountered the error;
'Error: --dataset should contain a pathname of a .loom or .h5 file. Add a '-h' flag for help. Execution halted'

The error occurred after running;

data("fibroblast_reprogramming_treutlein")

dataset <- wrap_expression(
  counts = fibroblast_reprogramming_treutlein$counts,
  expression = fibroblast_reprogramming_treutlein$expression
)
model_paga <- infer_trajectory(dataset = dataset, ti_slingshot())

The error;
Running singularity exec \
  'docker://dynverse/ti_slingshot:v1.0.3' \
  echo hi
Running /usr/local/bin/singularity exec \
  --containall -B \
  '/tmp/RtmpFqw2dH/file96f5f4e6b0f/:/copy_mount,/tmp/RtmpFqw2dH/file96f572d9577/tmp:/tmp2' \
  'docker://dynverse/ti_slingshot:v1.0.3' cp \
  /code/definition.yml /copy_mount/
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:a4d8138d0f6b5a441aaa533faf5fe0c3996a6ca42643c46f4402c7e8bda53742
Copying blob sha256:fb232e1cbf74f0fbcc4777cbfa268e7edacec9b944284fecb9a49a0717727371
Copying blob sha256:53a69644892140b394d496f0206f1e7caaffe83ac5c60245721b2d00189e0914
Copying blob sha256:0a98bf8e346bef6e92b33f0f28c5a473b6248a9ceb21686c5139485961033a8e
Copying blob sha256:80070ed7cf8857a7fa54e7506039f1dc8c03beb2ce337fb45c2c7a963d6c3336
Copying blob sha256:3dda0c19343b691057ef5913c40aa79e2d65e2ffb9cfead972003f055c52854a
Copying blob sha256:c8dedce96c17f919cd38e6d135303d3f2ca29bf0f73245671e1e3693bfa3169f
Copying blob sha256:33199d4ff47fef1ac4cd988b1a9e63341436fdfa00e6de3578d31031555385be
Copying blob sha256:7d44151ac2dae4a5c213f71c964418e5a18472aef650a4e3add71164e1d4ac82
Copying blob sha256:71c13904cc333688f9fa770fd95965f827949ea5c746b4dbb03e546fec3ad006
Copying blob sha256:a03a650d036654b42695ee1f175f5780d39ab41a25caebbd65a999aa946bc4e4
Copying blob sha256:d0e24af2427d84970f842be99c9e7320bebd79c6c408e05fdc8f98f5774cac4f
Copying blob sha256:509c796290f5400effd645bb08a804ec8ce8587687552a105d0a94b0f984208d
Copying blob sha256:fc7b41c3606c7d0cf3e66f4c7211f7ef0613e53fea45b733287465499f0bd216
Copying blob sha256:a0885e753793697a00322473263d6dea5c81d582b626c8cc3e6e34116de37a0b
Copying config sha256:9d4bf56ab1117a1d80d714edf530fc3ba45dafe7500d196577e833522a28c677
Writing manifest to image destination
Storing signatures
2021/10/27 22:38:10  info unpack layer: sha256:a4d8138d0f6b5a441aaa533faf5fe0c3996a6ca42643c46f4402c7e8bda53742
2021/10/27 22:38:10  warn rootless{usr/local/man} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:38:12  info unpack layer: sha256:fb232e1cbf74f0fbcc4777cbfa268e7edacec9b944284fecb9a49a0717727371
2021/10/27 22:38:16  warn rootless{usr/local/bin/install2.r} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:38:16  warn rootless{usr/local/bin/installGithub.r} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:38:16  warn rootless{usr/local/bin/r} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:38:20  info unpack layer: sha256:53a69644892140b394d496f0206f1e7caaffe83ac5c60245721b2d00189e0914
2021/10/27 22:38:28  warn rootless{usr/local/bin/pandoc} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:38:28  warn rootless{usr/local/bin/pandoc-citeproc} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:38:29  info unpack layer: sha256:0a98bf8e346bef6e92b33f0f28c5a473b6248a9ceb21686c5139485961033a8e
2021/10/27 22:38:29  info unpack layer: sha256:80070ed7cf8857a7fa54e7506039f1dc8c03beb2ce337fb45c2c7a963d6c3336
2021/10/27 22:38:29  info unpack layer: sha256:3dda0c19343b691057ef5913c40aa79e2d65e2ffb9cfead972003f055c52854a
2021/10/27 22:38:29  info unpack layer: sha256:c8dedce96c17f919cd38e6d135303d3f2ca29bf0f73245671e1e3693bfa3169f
2021/10/27 22:38:29  info unpack layer: sha256:33199d4ff47fef1ac4cd988b1a9e63341436fdfa00e6de3578d31031555385be
2021/10/27 22:38:44  info unpack layer: sha256:7d44151ac2dae4a5c213f71c964418e5a18472aef650a4e3add71164e1d4ac82
2021/10/27 22:38:44  info unpack layer: sha256:71c13904cc333688f9fa770fd95965f827949ea5c746b4dbb03e546fec3ad006
2021/10/27 22:38:44  info unpack layer: sha256:a03a650d036654b42695ee1f175f5780d39ab41a25caebbd65a999aa946bc4e4
2021/10/27 22:38:47  info unpack layer: sha256:d0e24af2427d84970f842be99c9e7320bebd79c6c408e05fdc8f98f5774cac4f
2021/10/27 22:38:50  info unpack layer: sha256:509c796290f5400effd645bb08a804ec8ce8587687552a105d0a94b0f984208d
2021/10/27 22:38:57  info unpack layer: sha256:fc7b41c3606c7d0cf3e66f4c7211f7ef0613e53fea45b733287465499f0bd216
2021/10/27 22:38:57  info unpack layer: sha256:a0885e753793697a00322473263d6dea5c81d582b626c8cc3e6e34116de37a0b
INFO:    Creating SIF file...
Error: INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:a4d8138d0f6b5a441aaa533faf5fe0c3996a6ca42643c46f4402c7e8bda53742
Copying blob sha256:fb232e1cbf74f0fbcc4777cbfa268e7edacec9b944284fecb9a49a0717727371
Copying blob sha256:53a69644892140b394d496f0206f1e7caaffe83ac5c60245721b2d00189e0914
Copying blob sha256:0a98bf8e346bef6e92b33f0f28c5a473b6248a9ceb21686c5139485961033a8e
Copying blob sha256:80070ed7cf8857a7fa54e7506039f1dc8c03beb2ce337fb45c2c7a963d6c3336
Copying blob sha256:3dda0c19343b691057ef5913c40aa79e2d65e2ffb9cfead972003f055c52854a
Copying blob sha256:c8dedce96c17f919cd38e6d135303d3f2ca29bf0f73245671e1e3693bfa3169f
Copying blob sha256:33199d4ff47fef1ac4cd988b1a9e63341436fdfa00e6de3578d31031555385be
Copying blob sha256:7d44151ac2dae4a5c213f71c964418e5a18472aef650a4e3add71164e1d4ac82
Copying blob sha256:71c13904cc333688f9fa770fd95965f827949ea5c746b4dbb03e546fec3ad006
Copying blob sha256:a03a650d036654b42695ee1f175f5780d39ab41a25caebbd65a999aa946bc4e4
Copying blob sha256:d0e24af2427d84970f842be99c9e7320bebd79c6c408e05fdc8f98f5774cac4f
Copying blob sha256:509c796290f5400effd645bb08a804ec8ce8587687552a105d0a94b0f984208d
Copying blob sha256:fc7b41c3606c7d0cf3e66f4c7211f7ef0613e53fea45b733287465499f0bd216
Copying blob sha256:a0885e753793697a00322473263d6dea5c81d582b626c8cc3e6e34116de37a0b
Copying config sha256:9d4bf56ab1117a1d80d714edf530fc3ba45dafe7500d196577e833522a28c677
Writing manifest to image destination
Storing signatures
2021/10/27 22:41:16  info unpack layer: sha256:a4d8138d0f6b5a441aaa533faf5fe0c3996a6ca42643c46f4402c7e8bda53742
2021/10/27 22:41:17  warn rootless{usr/local/man} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:41:19  info unpack layer: sha256:fb232e1cbf74f0fbcc4777cbfa268e7edacec9b944284fecb9a49a0717727371
2021/10/27 22:41:24  warn rootless{usr/local/bin/install2.r} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:41:24  warn rootless{usr/local/bin/installGithub.r} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:41:24  warn rootless{usr/local/bin/r} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:41:27  info unpack layer: sha256:53a69644892140b394d496f0206f1e7caaffe83ac5c60245721b2d00189e0914
2021/10/27 22:41:35  warn rootless{usr/local/bin/pandoc} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:41:35  warn rootless{usr/local/bin/pandoc-citeproc} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2021/10/27 22:41:36  info unpack layer: sha256:0a98bf8e346bef6e92b33f0f28c5a473b6248a9ceb21686c5139485961033a8e
2021/10/27 22:41:36  info unpack layer: sha256:80070ed7cf8857a7fa54e7506039f1dc8c03beb2ce337fb45c2c7a963d6c3336
2021/10/27 22:41:36  info unpack layer: sha256:3dda0c19343b691057ef5913c40aa79e2d65e2ffb9cfead972003f055c52854a
2021/10/27 22:41:36  info unpack layer: sha256:c8dedce96c17f919cd38e6d135303d3f2ca29bf0f73245671e1e3693bfa3169f
2021/10/27 22:41:36  info unpack layer: sha256:33199d4ff47fef1ac4cd988b1a9e63341436fdfa00e6de3578d31031555385be
2021/10/27 22:41:50  info unpack layer: sha256:7d44151ac2dae4a5c213f71c964418e5a18472aef650a4e3add71164e1d4ac82
2021/10/27 22:41:51  info unpack layer: sha256:71c13904cc333688f9fa770fd95965f827949ea5c746b4dbb03e546fec3ad006
2021/10/27 22:41:51  info unpack layer: sha256:a03a650d036654b42695ee1f175f5780d39ab41a25caebbd65a999aa946bc4e4
2021/10/27 22:41:54  info unpack layer: sha256:d0e24af2427d84970f842be99c9e7320bebd79c6c408e05fdc8f98f5774cac4f
2021/10/27 22:41:57  info unpack layer: sha256:509c796290f5400effd645bb08a804ec8ce8587687552a105d0a94b0f984208d
2021/10/27 22:42:04  info unpack layer: sha256:fc7b41c3606c7d0cf3e66f4c7211f7ef0613e53fea45b733287465499f0bd216
2021/10/27 22:42:04  info unpack layer: sha256:a0885e753793697a00322473263d6dea5c81d582b626c8cc3e6e34116de37a0b
INFO:    Creating SIF file...
Error: --dataset should contain a pathname of a .loom or .h5 file. Add a '-h' flag for help.
Execution halted

Error: Error during trajectory inference, see output above ↑↑↑

Thank you very much in advance

**Comment by kmh005** [comment]
I can also confirm the above error using a dataset from `wrap_expression` on a new install of dyno, please let me know if you need more info, looking forward to using the package!
```
object_counts<-Matrix::t(seur@assays$RNA@counts)
object_expression <- Matrix::t(seur@assays$RNA@data)

dataset <- wrap_expression(
  counts = object_counts,
  expression = object_expression,
)
myoblasts<-WhichCells(seur, idents="Myoblast")
dataset <- add_prior_information(
    dataset,
     start_id = myoblasts
)
```

slingshot
```
slingshot_model <- infer_trajectory(dataset, ti_slingshot())
Error: Error: --dataset should contain a pathname of a .loom or .h5 file. Add a '-h' flag for help.
Execution halted
```
and paga_tree

```
> paga_tree_model<-infer_trajectory(dataset, ti_paga_tree()) 
Error: R[write to console]: Error: --dataset should contain a pathname of a .loom or .h5 file. Add a '-h' flag for help.
Traceback (most recent call last):
  File "/code/run.py", line 24, in <module>
    task = dynclipy.main()
  File "/usr/local/lib/python3.7/site-packages/dynclipy/read.py", line 122, in main
    """)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 389, in __call__
    res = self.eval(p)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 192, in __call__
    .__call__(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 121, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface.py", line 773, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error: --dataset should contain a pathname of a .loom or .h5 file. Add a '-h' flag for help.
Error: Error during trajectory inference, see output above <U+2191><U+2191><U+2191>
```

```
 sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SeuratObject_4.0.0  Seurat_4.0.1        forcats_0.5.1      
 [4] stringr_1.4.0       dplyr_1.0.7         purrr_0.3.4        
 [7] readr_1.4.0         tidyr_1.1.4         tibble_3.1.4       
[10] ggplot2_3.3.5       tidyverse_1.3.0     dyno_0.1.2         
[13] dynwrap_1.2.2       dynplot_1.1.0       dynmethods_1.0.5   
[16] dynguidelines_1.0.1 dynfeature_1.0.0   

loaded via a namespace (and not attached):
  [1] utf8_1.2.2            reticulate_1.19       tidyselect_1.1.1     
  [4] htmlwidgets_1.5.2     grid_4.0.3            ranger_0.13.1        
  [7] Rtsne_0.15            devtools_2.3.2        munsell_0.5.0        
 [10] codetools_0.2-16      ica_1.0-2             future_1.21.0        
 [13] miniUI_0.1.1.1        withr_2.4.2           colorspace_2.0-0     
 [16] rstudioapi_0.13       ROCR_1.0-11           tensor_1.5           
 [19] listenv_0.8.0         polyclip_1.10-0       farver_2.1.0         
 [22] rprojroot_2.0.2       parallelly_1.24.0     vctrs_0.3.8          
 [25] generics_0.1.0        R6_2.5.1              GA_3.2.2             
 [28] graphlayouts_0.7.1    spatstat.utils_2.1-0  assertthat_0.2.1     
 [31] promises_1.1.1        scales_1.1.1          ggraph_2.0.4         
 [34] lmds_0.1.0            gtable_0.3.0          babelwhale_1.0.3     
 [37] globals_0.14.0        goftest_1.2-2         processx_3.5.2       
 [40] tidygraph_1.2.0       rlang_0.4.11.9001     splines_4.0.3        
 [43] lazyeval_0.2.2        spatstat.geom_2.1-0   broom_0.7.9          
 [46] yaml_2.2.1            reshape2_1.4.4        abind_1.4-5          
 [49] modelr_0.1.8          backports_1.2.1       httpuv_1.5.4         
 [52] tools_4.0.3           usethis_1.6.3         ellipsis_0.3.2       
 [55] spatstat.core_2.1-2   RColorBrewer_1.1-2    sessioninfo_1.1.1    
 [58] ggridges_0.5.2        Rcpp_1.0.7            plyr_1.8.6           
 [61] ps_1.4.0              prettyunits_1.1.1     rpart_4.1-15         
 [64] deldir_0.2-3          pbapply_1.4-3         viridis_0.5.1        
 [67] cowplot_1.1.1         dynparam_1.0.2        zoo_1.8-8            
 [70] haven_2.3.1           ggrepel_0.9.1         cluster_2.1.0        
 [73] fs_1.5.0              magrittr_2.0.1        data.table_1.13.2    
 [76] scattermore_0.7       carrier_0.1.0         lmtest_0.9-38        
 [79] reprex_0.3.0          RANN_2.6.1            fitdistrplus_1.1-1   
 [82] matrixStats_0.58.0    pkgload_1.1.0         hms_0.5.3            
 [85] patchwork_1.1.1       mime_0.9              xtable_1.8-4         
 [88] readxl_1.3.1          gridExtra_2.3         testthat_3.0.0       
 [91] compiler_4.0.3        KernSmooth_2.23-17    crayon_1.4.1         
 [94] htmltools_0.5.1.1     proxyC_0.2.1          mgcv_1.8-33          
 [97] later_1.1.0.1         RcppParallel_5.0.2    lubridate_1.7.9.2    
[100] DBI_1.1.0             tweenr_1.0.1          dbplyr_2.0.0         
[103] MASS_7.3-53           Matrix_1.2-18         cli_3.0.1            
[106] parallel_4.0.3        igraph_1.2.6          pkgconfig_2.0.3      
[109] plotly_4.9.2.1        spatstat.sparse_2.0-0 xml2_1.3.2           
[112] foreach_1.5.1         dynutils_1.0.9        rvest_0.3.6          
[115] callr_3.5.1           digest_0.6.27         dyndimred_1.0.4      
[118] sctransform_0.3.2     RcppAnnoy_0.0.18      spatstat.data_2.1-0  
[121] cellranger_1.1.0      leiden_0.3.5          uwot_0.1.9.9000      
[124] curl_4.3              shiny_1.5.0           nlme_3.1-149         
[127] lifecycle_1.0.1       jsonlite_1.7.2        desc_1.2.0           
[130] viridisLite_0.4.0     fansi_0.5.0           pillar_1.6.3         
[133] lattice_0.20-41       fastmap_1.0.1         httr_1.4.2           
[136] pkgbuild_1.1.0        survival_3.2-7        glue_1.4.2           
[139] remotes_2.2.0         png_0.1-7             iterators_1.0.13     
[142] ggforce_0.3.2         stringi_1.7.4         memoise_1.1.0        
[145] irlba_2.3.3           future.apply_1.7.0   
```

**Comment by CQgit** [comment]
same issue.

`Error: Error: --dataset should contain a pathname of a .loom or .h5 file. Add a '-h' flag for help.`

`
> sessionInfo()
R version 4.1.2 Patched (2021-12-16 r81386)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur/Monterey 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] shiny_1.7.1         forcats_0.5.1       stringr_1.4.0      
 [4] dplyr_1.0.7         purrr_0.3.4         readr_2.1.1        
 [7] tidyr_1.1.4         tibble_3.1.6        ggplot2_3.3.5      
[10] tidyverse_1.3.1     dyno_0.1.2          dynwrap_1.2.2      
[13] dynplot_1.1.2       dynmethods_1.0.5    dynguidelines_1.0.1
[16] dynfeature_1.0.0   

loaded via a namespace (and not attached):
  [1] colorspace_2.0-2   ellipsis_0.3.2     rprojroot_2.0.2   
  [4] dynparam_1.0.2     fs_1.5.2           rstudioapi_0.13   
  [7] farver_2.1.0       remotes_2.4.2      graphlayouts_0.7.2
 [10] waldo_0.3.1        dynutils_1.0.9     ggrepel_0.9.1     
 [13] fansi_0.5.0        lubridate_1.8.0    ranger_0.13.1     
 [16] xml2_1.3.3         codetools_0.2-18   cachem_1.0.6      
 [19] polyclip_1.10-0    jsonlite_1.7.2     broom_0.7.10      
 [22] dbplyr_2.1.1       ggforce_0.3.3      compiler_4.1.2    
 [25] httr_1.4.2         backports_1.4.1    assertthat_0.2.1  
 [28] Matrix_1.4-0       fastmap_1.1.0      cli_3.1.0         
 [31] later_1.3.0        tweenr_1.0.2       htmltools_0.5.2   
 [34] tools_4.1.2        igraph_1.2.10      gtable_0.3.0      
 [37] glue_1.6.0         reshape2_1.4.4     Rcpp_1.0.7        
 [40] GA_3.2.2           cellranger_1.1.0   jquerylib_0.1.4   
 [43] vctrs_0.3.8        iterators_1.0.13   ggraph_2.0.5      
 [46] ps_1.6.0           testthat_3.1.1     rvest_1.0.2       
 [49] mime_0.12          lifecycle_1.0.1    akima_0.6-2.3     
 [52] irlba_2.3.5        MASS_7.3-54        scales_1.1.1      
 [55] tidygraph_1.2.0    babelwhale_1.0.3   hms_1.1.1         
 [58] promises_1.2.0.1   yaml_2.2.1         gridExtra_2.3     
 [61] sass_0.4.0         dyndimred_1.0.4    stringi_1.7.6     
 [64] desc_1.4.0         foreach_1.5.1      rlang_0.4.12      
 [67] pkgconfig_2.0.3    lattice_0.20-45    fontawesome_0.2.2 
 [70] patchwork_1.1.1    processx_3.5.2     tidyselect_1.1.1  
 [73] plyr_1.8.6         magrittr_2.0.1     R6_2.5.1          
 [76] generics_0.1.1     DBI_1.1.1          pillar_1.6.4      
 [79] haven_2.4.3        carrier_0.1.0      withr_2.4.3       
 [82] proxyC_0.2.4       sp_1.4-6           modelr_0.1.8      
 [85] crayon_1.4.2       shinyWidgets_0.6.2 lmds_0.1.0        
 [88] utf8_1.2.2         tzdb_0.2.0         viridis_0.6.2     
 [91] grid_4.1.2         readxl_1.3.1       reprex_2.0.1      
 [94] digest_0.6.29      xtable_1.8-4       httpuv_1.6.4      
 [97] RcppParallel_5.1.4 munsell_0.5.0      viridisLite_0.4.0 
[100] bslib_0.3.1        shinyjs_2.0.0     
`

**Comment by CQgit** [comment]
problem solved 

`install.packages("hdf5r")`

**Comment by erzakiev** [comment]
why is this happening? So many people (incl me) had this problem. Is `hdf5r` not a dependency for `dyno`?

**Comment by szcf-weiya** [comment]
same issue when following the "quick start" (https://dynverse.org/users/2-quick_start/) with a completely new install of `dyno`. 
Installing `hdf5r` solved!
