### ISSUE TITLE
Error from running paga method

### ISSUE THREAD

**Issue by DHGK** [dynverse/dyno#54]
Hi dyno community,

I was trying to run slingshot and paga methods on my data. Since paga method required a prior, I set "start_id" based on some assumptions. Using the dataset, I could get slingshot trajectory without any issue, but for the paga method I got following issue and not so sure how to interpret this error report. Has anyone got the same error before and what would be a way to resolve this? Thanks!!

R[write to console]: Error in parse_args(parser, args = args) : 

  Error in getopt(spec = spec, opt = args) : 
  long flag "use_priors" is invalid
Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> parse_args

Traceback (most recent call last):
  File "/code/run.py", line 22, in <module>
    task = dynclipy.main()
  File "/usr/local/lib/python3.7/site-packages/dynclipy/read.py", line 123, in main
    """)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 389, in __call__
    res = self.eval(p)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 192, in __call__
    .__call__(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 121, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface.py", line 773, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in parse_args(parser, args = args) : 
  Error in getopt(spec = spec, opt = args) : 
  long flag "use_priors" is invalid
Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> parse_args

Error: Error during trajectory inference 
R[write to console]: Error in parse_args(parser, args = args) : 
  Error in getopt(spec = spec, opt = args) : 
  long flag "use_priors" is invalid
Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> parse_args

Traceback (most recent call last):
  File "/code/run.py", line 22, in <module>
    task = dynclipy.main()
  File "/usr/local/lib/python3.7/site-packages/dynclipy/read.py", line 123, in main
    """)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 389, in __call__
    res = self.eval(p)
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 192, in __call__
    .__call__(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 121, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 28, in _
    cdata = function(*args, **kw

**Comment by rcannood** [comment]
Hello DHGK!

This problem occurs because the ti_paga container is outdated. Could you update dynmethods (`devtools::install_github("dynverse/dynmethods")`)? This should update the ti_paga container next time you try to use it.

Let us know whether this solved your problem.
Robrecht

**Comment by ryandhindsa** [comment]
Hi, I was having the same problem. I ran `devtools::install_github("dynverse/dynmethods")`, but when I tried inferring the trajectory, I got a new error:

Error response from daemon: manifest for dynverse/ti_paga_tree:v0.9.9.04 not found

**Comment by rcannood** [comment]
Hey @ryandhindsa,

This is because ti_paga and ti_paga_tree currently [cannot build anymore](https://travis-ci.org/dynverse/ti_paga/builds/544731805) due to a problem with scanpy (theislab/scanpy#688). 

I was able to perform some magic tricks and managed to create an updated ti_paga_tree:v0.9.9.04 for you to enjoy ;) 

Can you confirm this is working for you?

Robrecht

**Comment by rcannood** [comment]
This problem should have been fixed, closing this issue.
